---
driver:
  name: lxd_cli

transport:
  name: sftp
  ### try to avoid random "TIMING: scp async upload (Kitchen::Transport::Ssh)"
  ### default timeout 15s, alternate sftp/kitchen-sync
  #  name: ssh
  #  keepalive: true
  #  keepalive_interval: 5
  #  timout: 30

driver_config:
  customize:
    # cpus: 2
    memory: 1024

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_cfg_path: test/vagrant/ansible.cfg
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
    attributes:
  - name: default-HEAD
    run_list:
    attributes:
