---
driver:
  name: lxd_cli

driver_config:
  customize:
#  cpus: 2
  memory: 1024

## try to avoid random "TIMING: scp async upload (Kitchen::Transport::Ssh)"
## default timeout 15s, alternate sftp/kitchen-sync
transport:
  name: ssh
  keepalive: true
  keepalive_interval: 5
  timout: 30
#  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
#  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: ubuntu-12.04
#  - name: centos-7
#  - name: centos-6
## "Failed to complete #create action: [Broken pipe] on default-alpine-34"
## do we have python2 in default image?
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:

