---
## from https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml
sudo: required

env:
  - distribution: ubuntu
    version: 20.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
    if: branch =~ /^devel*/
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
  - distribution: ubuntu
    version: 18.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default-HEAD

services:
  - docker

before_install:
  # - sudo apt-get update
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  - env
  - pwd
  - find -ls
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  - cp test/travis/initctl_faker test/
  # Customize container
  - 'sudo docker build --rm=true --file=test/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible test'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD%/*}":/etc/ansible/roles:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.sift/test/integration/${suite}/default.yml --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm TRAVIS=true ansible-playbook /etc/ansible/roles/juju4.sift/test/integration/${suite}/default.yml -vvvv'
#  - 'travis_wait 30 sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.sift/test/integration/${suite}/default.yml'

  # Test role idempotence.
## known fail + disable (too long for travis, else)
#  - >
#    sudo docker exec "$(cat ${container_id})" env TERM=xterm TRAVIS=true ansible-playbook /etc/ansible/roles/juju4.sift/test/integration/${suite}/default.yml
#    | tee /tmp/idempotency.log
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)

  # serverspec tests
## travis/docker: Errno::EROFS: Read-only file system @ dir_s_mkdir - /etc/ansible/roles/juju4.sift/test/integration/${suite}/serverspec/.bundle
#  - 'sudo docker exec --tty "$(cat ${container_id})" /etc/ansible/roles/juju4.sift/test/integration/${suite}/serverspec/run-local-tests.sh'

after_failure:
  # Check what happened on systems.
  - 'sudo docker exec --tty "$(cat ${container_id})" tail -100 /var/log/syslog'

after_script:
  # check state of some packages between sift/gift/ubuntu
  - 'sudo docker exec --tty "$(cat ${container_id})" apt show libtsk-dev -a'
  - 'sudo docker exec --tty "$(cat ${container_id})" apt show libtsk13 -a'
  - 'sudo docker exec --tty "$(cat ${container_id})" apt show libewf -a'
  - 'sudo docker exec --tty "$(cat ${container_id})" apt show libewf2 -a'
  - 'sudo docker exec --tty "$(cat ${container_id})" apt-get install -y apt-rdepends'
  - 'sudo docker exec --tty "$(cat ${container_id})" apt-rdepends libtsk-dev'
  - 'sudo docker exec --tty "$(cat ${container_id})" ls /home/sansforensics'
  - 'sudo docker exec --tty "$(cat ${container_id})" ls /home/sansforensics/Desktop'
  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
