---

- name: Set fact for bulk_extractor
  ansible.builtin.set_fact:
    be_path: /root/bulk_extractor

- name: git clone bulk extractor
  ansible.builtin.git:
    repo: https://github.com/simsong/bulk_extractor.git
    dest: "{{ be_path }}"
    version: "{{ sift_bulkextractor_src_version }}"
    update: no

- name: ensure development tools are present
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - autoconf
    - libexpat1-dev
    - libssl-dev
    - libtsk-dev
    - libxml2-utils
    - make
    - pkg-config
    # for hashdb
    - libtool-bin
    # python-dev or python3-dev. taken from global packages list
    # - python-dev
    - swig
    - libewf-dev
    - libbz2-dev
    - zlib1g-dev
  register: pkg_result
  until: pkg_result is success

- name: ensure symlink for lib/tsk3
  ansible.builtin.file:
    src: /usr/include/tsk
    dest: /usr/include/tsk3
    mode: '0755'
    state: link

- name: build bulk-extractor
  ansible.builtin.command: "{{ item.c }}"
  args:
    chdir: "{{ be_path }}"
    creates: "{{ item.f }}"
  with_items:
    - { c: 'sh bootstrap.sh', f: "{{ be_path }}/configure" }
    - { c: './configure --prefix=/usr/local', f: "{{ be_path }}/Makefile" }
    - { c: make, f: "{{ be_path }}/src/bulk_extractor" }
    - { c: 'make install', f: '/usr/local/bin/bulk_extractor' }
