---

- name: Check current pip version
  ansible.builtin.shell: |
    set -o pipefail
    {{ pip_bin }} --version | sed "s/pip \(.*\) from .*/\1/"
  args:
    executable: /bin/bash
  changed_when: false
  register: pipv

- name: Debug | pip version
  ansible.builtin.debug: var=pipv.stdout

## does not seem to be handled well by ansible pip module
- name: Old pip
  block:

    - name: Upgrade pip to latest
      ansible.builtin.command: "{{ pip_bin }} install --upgrade pip"
      when: ansible_os_family != "Debian"

    - name: Upgrade setuptools to latest
      ansible.builtin.command: "{{ pip_bin }} install --upgrade setuptools"
      when: ansible_os_family != "Debian"

  when: pipv.stdout is version_compare('10.1', '<')
