---

- name: copy sift foremost conf to /etc
  copy:
    src: "{{ sift_files }}/files/foremost/foremost.conf"
    dest: /etc/foremost.conf
    remote_src: true

- name: Check if /usr/share/tsk/sorter exists
  stat: path=/usr/share/tsk/sorter
  register: tsksorter
- name: list sift tsk sorter files
  command: "find {{ sift_files }}/files/sorter/ -type f"
  register: sorter
  changed_when: false
  ignore_errors: true
- name: copy sift tsk sorter files to package location
  copy:
    src: "{{ item }}"
    dest: /usr/share/tsk/sorter/
    remote_src: true
  with_fileglob:
    - "{{ sift_files }}/files/sorter/*.sort"
  when: tsksorter.stat.exists

- name: copy sift samba files
  copy:
    src: "{{ sift_files }}/files/samba/smb.conf"
    dest: /etc/samba/smb.conf
    remote_src: true

## FIXME! upstream: some files are there twice in both wbtools and scripts:
##      extract_mft_record_slack.py, ShellItems.py, shellbags.py
- name: copy sift files for various tools
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: true
  with_fileglob:
    - "{{ sift_files }}/files/pdf-tools/*"
    - "{{ sift_files }}/files/page-brute/*.py"

- name: Check if volatility is present
  stat: path=/usr/lib/python2.7/dist-packages/volatility
  register: vol
- block:
    - name: copy sift volatility files
      copy:
        src: "{{ item }}"
        dest: /usr/lib/python2.7/dist-packages/volatility/plugins/
        mode: '0644'
        remote_src: true
      with_fileglob:
        - "{{ sift_files }}/files/volatility/*.py"

## why? https://github.com/sans-dfir/sift-files/blob/master/install.sh
    - name: remove volatility javarat plugins
      file: dest=/usr/lib/python2.7/dist-packages/volatility/plugins/javarat.py state=absent

  when: vol.stat.exists and sift_include_volplugins

- name: ensure directories exist
  file: dest={{ item }} state=directory
  with_items:
    - /usr/share/sift/resources
    - /usr/share/sift/images
    - /usr/share/sift/audio
    - /usr/share/sift/other
    - /usr/share/sift/scripts
    - /usr/share/regripper

- name: copy sift tools directories to /usr/share/sift
  copy:
    src: "{{ item }}"
    dest: /usr/share/sift/
    remote_src: true
  with_items:
    - "{{ sift_files }}/files/sift/scripts"
    - "{{ sift_files }}/files/sift/other"
    - "{{ sift_files }}/files/sift/images"
    - "{{ sift_files }}/files/sift/audio"
    - "{{ sift_files }}/files/sift/resources"

- name: copy regripper files to /usr/share/regripper
  copy:
    src: "{{ item }}"
    dest: /usr/share/regripper/
    mode: '0755'
    remote_src: true
  with_items:
    - "{{ sift_files }}/files/regripper/rip.pl"

- name: ensure /usr/local/bin/id absent
  file: dest=/usr/local/bin/id state=absent

- name: sift fixubuntu.sh
  command: bash fixubuntu.sh
  args:
    chdir: "{{ sift_files }}/files"
  ignore_errors: true
