---
## Post-install actions for packages from SIFT ppa

- stat: path=/root/.dos2unix_regripper
  register: d2u_rr
- name: Fixing Regripper Files
  shell: "dos2unix -ascii /usr/share/regripper/*"
  when: not d2u_rr.stat.exists
- file: path=/root/.dos2unix_regripper state=touch
  when: not d2u_rr.stat.exists
- stat: path=/usr/share/regripper/plugins/usrclass-all
  register: rrusr
- stat: path=/usr/share/regripper/plugins/ntuser-all
  register: rrnt
- command: mv /usr/share/regripper/plugins/usrclass-all /usr/share/regripper/plugins/usrclass
  when: rrusr.stat.exists
- command: mv /usr/share/regripper/plugins/ntuser-all /usr/share/regripper/plugins/ntuser
  when: rrnt.stat.exists
- file: path="/usr/share/regripper/rip.pl" mode=0775
#- command: chmod -R 755 /usr/share/regripper/plugins
- file: dest=/usr/share/regripper/plugins state=directory mode=0755 recurse=yes

- name: Xenial | force-depends bulk-extractor install
  apt:
    name: bulk-extractor
    state: present
    dpkg_options: '--force-depends'
  when: ansible_distribution_release == 'xenial'
  ignore_errors: true

