---

- name: Creating sansforensics group
  ansible.builtin.group:
    name: "{{ sift_user }}"
## used as samba guest
- name: Creating sansforensics generic account
  ansible.builtin.user:
    name: "{{ sift_user }}"
    password: "{{ sift_pass }}"
    groups: "{{ sift_user }},sudo"
    append: yes

- name: Add authorized keys for sift_user
  ansible.posix.authorized_key:
    user: "{{ sift_user }}"
    key: "{{ item }}"
  loop: "{{ sift_public_keys }}"
  when: sift_public_keys is defined and sift_public_keys
  become: yes

- name: Import sift-repos
  ansible.builtin.import_tasks: sift-repos.yml

- name: SIFT | accept Microsoft EULA for ttf-mscorefonts-installer
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: 'msttcorefonts/accepted-mscorefonts-eula'
    value: 'true'
    vtype: 'boolean'

- name: SIFT | Remove conflicting packages
  ansible.builtin.apt:
    name: "{{ sift_conflict_packages | default([]) }}"
    state: absent

- name: SIFT | packages install
  ansible.builtin.apt:
    name: "{{ sift_packages + sift_perl_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify:
    - Updating ClamAV Signatures
  async: 3600
  poll: 60
  register: pkg_result
  until: pkg_result is success

- name: SIFT | gift+sift ppa packages install
  ansible.builtin.apt:
    name: "{{ sift_ppa_packages + gift_ppa_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: pkg_result
  until: pkg_result is success

- name: SIFT | apache2 packages install
  ansible.builtin.apt:
    name: "apache2"
    state: "present"
  when: sift_webserver is defined and sift_webserver == 'apache2'
  register: pkg_result
  until: pkg_result is success

- name: SIFT | docker packages install
  ansible.builtin.apt:
    name: "{{ sift_docker_pkg }}"
    state: "present"
  when: sift_docker
  register: pkg_result
  until: pkg_result is success

## missing dependencies in some case?
- name: Debian | gedit install
  ansible.builtin.apt:
    name: gedit
    state: present
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- name: Import sift-arc
  ansible.builtin.import_tasks: sift-arc.yml

- name: Check if pescan is present
  ansible.builtin.stat:
    path: /usr/bin/pescan
  register: rpev
- name: Debian | pev install (only if not remnux-pev)
  ansible.builtin.apt:
    name: pev
    state: present
  when: not rpev.stat.exists
  register: pkg_result
  until: pkg_result is success

- name: Import python-externally-managed
  ansible.builtin.import_tasks: python-externally-managed.yml
- name: Include pip-upgrade
  ansible.builtin.include_tasks: pip-upgrade.yml

- name: Install pip packages dependencies
  ansible.builtin.package:
    name: "{{ sift_pip_packages_deps + python_deps }}"
    state: "present"
  register: pkg_result
  until: pkg_result is success
- name: Install pip virtualenv
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
    state: present
    virtualenv: "{{ sift_virtualenv }}"
  register: pkg_result
  until: pkg_result is success
- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ sift_pip_packages }}"
    state: present
    virtualenv: "{{ sift_virtualenv }}"
  register: pkg_result
  until: pkg_result is success

- name: Install perl modules
  community.general.cpanm:
    name: "{{ item }}"
  with_items: "{{ sift_perl_cpanm_packages }}"
  register: pkg_result
  until: pkg_result is success

- name: Fetch SIFT files
  ansible.builtin.git:
    repo: https://github.com/sans-dfir/sift-saltstack.git
    dest: "{{ sift_files }}"
    version: "{{ sift_saltstack_version | default('9913b8bca7226ad7b642f95d4d6abdba1a9bd9e5') }}"
    recursive: no
    update: no
    force: no
- name: Include sift-files-install
  ansible.builtin.include_tasks: sift-files-install.yml

- name: Create SIFT folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '01775'
    owner: "{{ sift_user }}"
    group: "{{ sift_user }}"
  with_items:
    - /cases
- name: Create SIFT folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /mnt/usb
    - /mnt/vss
    - /mnt/shadow
    - /mnt/windows_mount
    - /mnt/e01
    - /mnt/aff
    - /mnt/ewf
    - /mnt/bde
    - /mnt/iscsi
    - /mnt/windows_mount1
    - /mnt/windows_mount2
    - /mnt/windows_mount3
    - /mnt/windows_mount4
    - /mnt/windows_mount5
    - /mnt/ewf_mount1
    - /mnt/ewf_mount2
    - /mnt/ewf_mount3
    - /mnt/ewf_mount4
    - /mnt/ewf_mount5
- name: Create SIFT folders
  ansible.builtin.file:
    path: "/mnt/shadow/vss{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
- name: Create SIFT folders
  ansible.builtin.file:
    path: "/mnt/shadow_mount/vss{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

- name: Add extra device loop backs
  ansible.builtin.lineinfile:
    dest: /etc/rc.local
    regexp: 'seq 8 100'
    line: 'for i in `seq 8 100`; do mknod /dev/loop$i b 7 $i; done'
    mode: '0644'
    backup: yes
    create: yes

- name: Ensure user Desktop directory exists
  ansible.builtin.file:
    dest: "/home/{{ sift_user }}/Desktop"
    state: directory
    mode: 0700
    owner: "{{ sift_user }}"

- name: Setting symlinks
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    mode: '0644'
    state: link
  with_items:
    - { src: '/usr/bin/gedit', path: '/usr/bin/kedit' }
    - { src: '/etc/foremost.conf', path: '/usr/local/etc/foremost.conf' }
    # - { src: '/usr/bin/iscsiadm', path: '/sbin/iscsiadm' }
    - "{{ gift_ppa_symlinks }}"
    - "{{ sift_ppa_symlinks }}"

- name: Check if /etc/apt/apt.conf.d/10periodic exists
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/10periodic
  register: periodic
- name: Disable automated package update
  ansible.builtin.lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    regexp: '^APT::Periodic::Update-Package-Lists'
    line: 'APT::Periodic::Update-Package-Lists "0";'
    mode: '0644'
  when: periodic.stat.exists

- name: Ensure current user is used for samba
  ansible.builtin.replace:
    dest: /etc/samba/smb.conf
    regexp: 'SIFT_USER'
    replace: "{{ sift_user }}"
    mode: '0644'
  notify:
    - Restart samba smbd
    - Restart samba nmbd

- name: Check timezone setting
  ansible.builtin.slurp:
    src: /etc/timezone
  register: timezone
## FIXME: not idempotent??? = adding when
- name: Set timezone variables
  community.general.timezone:
    name: "{{ tz }}"
  notify:
    - update timezone
  when: "tz not in timezone['content'] | b64decode"

- name: Include sift-ppa
  ansible.builtin.include_tasks: sift-ppa.yml

- name: Import bulk-extractor
  ansible.builtin.import_tasks: bulk-extractor.yml
  when: sift_bulkextractor_source | bool
- name: Install bulk-extractor package - sift ppa
  ansible.builtin.package:
    name: bulk-extractor
    state: present
  register: pkg_result
  until: pkg_result is success
  when:
    - not sift_bulkextractor_source | bool
    - (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int <= 20)

- name: Setting noclobber for sift_user and root
  ansible.builtin.lineinfile:
    dest: "{{ item }}"
    regexp: '^set -o noclobber'
    line: 'set -o noclobber'
    mode: '0600'
  with_items:
    - "/home/{{ sift_user }}/.bashrc"
    - /root/.bashrc
- name: Configuring Aliases for sift_user and root
  ansible.builtin.lineinfile:
    dest: "{{ item.d }}"
    regexp: '^alias mountwin='
    line: 'alias mountwin="mount -o ro,loop,show_sys_files,streams_interface=windows"'
    mode: '0600'
    owner: "{{ item.o }}"
    create: yes
  with_items:
    - { d: "/home/{{ sift_user }}/.bash_aliases", o: "{{ sift_user }}" }
    - { d: /root/.bash_aliases, o: root }

- name: Setting up useful links on sift_user Desktop
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    mode: '1775'
    owner: "{{ sift_user }}"
    follow: no
    state: link
  with_items:
    - { src: '/cases', path: "/home/{{ sift_user }}/Desktop/cases" }
    - { src: '/mnt', path: "/home/{{ sift_user }}/Desktop/mount_points" }

## FIXME! not idempotent
# - name: Cleaning up broken symlinks on Desktop
#   command: "find -L /home/{{ sift_user }}/Desktop -type l -delete"

- name: Adding all SIFT Resources to Desktop
  ansible.builtin.file:
    src: "/usr/share/sift/resources/{{ item }}"
    dest: "/home/{{ sift_user }}/Desktop/{{ item | basename }}"
    mode: '0644'
    owner: "{{ sift_user }}"
    follow: no
    state: link
    # with_fileglob:
    #   - /usr/share/sift/resources/*.pdf
  with_items:
    - Evidence-of-Poster.pdf
    - Find-Evil-Poster.pdf
    - SANS-DFIR.pdf
    - Smartphone-Forensics-Poster.pdf
    - memory-forensics-cheatsheet.pdf
    - network-forensics-cheatsheet.pdf
    - sift-cheatsheet.pdf
    - windows-to-unix-cheatsheet.pdf

- name: Include sift-cli
  ansible.builtin.include_tasks: sift-cli.yml
