---
## Post-install actions for packages from SIFT ppa

- name: Check dos2unix regripper marker
  stat: path=/root/.dos2unix_regripper
  register: d2u_rr
- name: Fixing Regripper Files
  shell: "dos2unix -ascii /usr/share/regripper/*"
  when: not d2u_rr.stat.exists
- name: Add dos2unix regripper marker
  file: path=/root/.dos2unix_regripper state=touch
  when: not d2u_rr.stat.exists
- name: Check if /usr/share/regripper/plugins/usrclass-all exists
  stat: path=/usr/share/regripper/plugins/usrclass-all
  register: rrusr
- name: Check if /usr/share/regripper/plugins/ntuser-all exists
  stat: path=/usr/share/regripper/plugins/ntuser-all
  register: rrnt
- name: Link regripper usrclass
  file:
    src: /usr/share/regripper/plugins/usrclass-all
    dest: /usr/share/regripper/plugins/usrclass
    state: link
  when: rrusr.stat.exists
- name: Link regripper ntuser
  file:
    src: /usr/share/regripper/plugins/ntuser-all
    dest: /usr/share/regripper/plugins/ntuser
    state: link
  when: rrnt.stat.exists
- name: Ensure rip.pl permissions
  file:
    path: "/usr/share/regripper/rip.pl"
    mode: '0775'
#- command: chmod -R 755 /usr/share/regripper/plugins
- name: Ensure regripper plugins permissions
  file:
    dest: /usr/share/regripper/plugins
    state: directory
    mode: '0755'
    recurse: yes
