---

- name: copy sift foremost conf to /etc
  copy:
    src: "{{ sift_files }}/sift/files/foremost/foremost.conf"
    dest: /etc/foremost.conf
    mode: '0644'
    remote_src: true

- name: Check if /usr/share/tsk/sorter exists
  stat: path=/usr/share/tsk/sorter
  register: tsksorter
- name: list sift tsk sorter files
  command: "find {{ sift_files }}/sift/files/sorter/ -type f"
  register: sorter
  changed_when: false
  ignore_errors: true
- name: copy sift tsk sorter files to package location
  copy:
    src: "{{ item }}"
    dest: /usr/share/tsk/sorter/
    mode: '0644'
    remote_src: true
    # with_fileglob:
    #   - "{{ sift_files }}/sift/files/sorter/*.sort"
  with_items: "{{ sorter.stdout_lines }}"
  when: tsksorter.stat.exists

- name: copy sift samba files
  copy:
    src: "{{ sift_files }}/sift/files/samba/smb.conf"
    dest: /etc/samba/smb.conf
    mode: '0644'
    remote_src: true

- name: list sift pdf-tools & page-brute files
  command: "find {{ sift_files }}/sift/files/pdf-tools/ {{ sift_files }}/sift/files/page-brute/ -type f"
  register: find2
  changed_when: false
  ignore_errors: true
- name: copy sift files for various tools
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: true
    # with_fileglob:
    #   - "{{ sift_files }}/sift/files/pdf-tools/*"
    #   - "{{ sift_files }}/sift/files/page-brute/*.py"
  with_items: "{{ find2.stdout_lines }}"

- name: Check if volatility is present
  stat: path=/usr/lib/python2.7/dist-packages/volatility
  register: vol
- block:
    - name: list sift volatility files
      command: "find {{ sift_files }}/sift/files/volatility/ -type f -iname '*.py'"
      register: find3
      changed_when: false
      ignore_errors: true
    - name: copy sift volatility files
      copy:
        src: "{{ item }}"
        dest: /usr/lib/python2.7/dist-packages/volatility/plugins/
        mode: '0644'
        remote_src: true
        # with_fileglob:
        #   - "{{ sift_files }}/sift/files/volatility/*.py"
      with_items: "{{ find3.stdout_lines }}"

    ## why? https://github.com/sans-dfir/sift-files/blob/master/install.sh
    - name: remove volatility javarat plugins
      file: dest=/usr/lib/python2.7/dist-packages/volatility/plugins/javarat.py state=absent

  when: vol.stat.exists and sift_include_volplugins

- name: ensure directories exist
  file:
    dest: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /usr/share/sift/resources
    - /usr/share/sift/images
    - /usr/share/sift/audio
    - /usr/share/sift/other
    - /usr/share/sift/scripts
    - /usr/share/regripper

- name: copy sift tools directories to /usr/share/sift
  synchronize:
    src: "{{ item }}"
    dest: /usr/share/sift/
  with_items:
    - "{{ sift_files }}/sift/files/sift/scripts"
    - "{{ sift_files }}/sift/files/sift/other"
    - "{{ sift_files }}/sift/files/sift/images"
    - "{{ sift_files }}/sift/files/sift/audio"
    - "{{ sift_files }}/sift/files/sift/resources"
  delegate_to: "{{ inventory_hostname }}"

- name: copy regripper files to /usr/share/regripper
  copy:
    src: "{{ sift_files }}/sift/files/regripper/rip.pl"
    dest: /usr/share/regripper/
    mode: '0755'
    remote_src: true

- name: ensure /usr/local/bin/id absent
  file: dest=/usr/local/bin/id state=absent

- name: sift fixubuntu.sh  # noqa 301
  command: bash fixubuntu.sh
  args:
    chdir: "{{ sift_files }}/sift/files"
  ignore_errors: true
