---

- name: copy sift foremost conf to /etc
  copy:
    src: /tmp/sift-files/foremost/foremost.conf
    dest: /etc/foremost.conf

- stat: path=/usr/share/tsk/sorter
  register: tsksorter
- name: list sift tsk sorter files
  command: find /tmp/sift-files/sorter/ -type f
  register: sorter
  changed_when: false
  ignore_errors: true
- name: copy sift tsk sorter files to package location
  copy:
    src: "{{ item }}"
    dest: /usr/share/tsk/sorter/
  with_fileglob:
    - "/tmp/sift-files/sorter/*.sort"
  when: tsksorter.stat.exists

- name: copy sift samba files
  copy:
    src: /tmp/sift-files/samba/smb.conf
    dest: /etc/samba/smb.conf

## FIXME! upstream: some files are there twice in both wbtools and scripts: extract_mft_record_slack.py, ShellItems.py, shellbags.py
- name: copy sift files for various tools
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
  with_fileglob:
    - /tmp/sift-files/wbtools/*
    - /tmp/sift-files/pdf-tools/*
    - /tmp/sift-files/scripts/*
    - /tmp/sift-files/densityscout/densityscout
## FIXME! submodule missing...
##    - /tmp/sift-files/pe_carver/*.py
##    - /tmp/sift-files/page_brute/*.py     # empty?
    - /tmp/sift-files/java_idx_parser/*.py
    - /tmp/sift-files/sift/scripts/*

- stat: path=/usr/lib/python2.7/dist-packages/volatility
  register: vol
- block:
    - name: copy sift volatility files
      copy:
        src: "{{ item }}"
        dest: /usr/lib/python2.7/dist-packages/volatility/plugins/
        mode: '0644'
      with_fileglob:
        - /tmp/sift-files/volatility/*.py

## why? https://github.com/sans-dfir/sift-files/blob/master/install.sh
    - name: remove volatility javarat plugins
      file: dest=/usr/lib/python2.7/dist-packages/volatility/plugins/javarat.py state=absent

  when: vol.stat.exists and sift_include_volplugins

- name: ensure directories exist
  file: dest={{ item }} state=directory
  with_items:
    - /usr/share/sift/resources
    - /usr/share/sift/images
    - /usr/share/sift/audio
    - /usr/share/sift/other
    - /usr/share/sift/scripts
    - /usr/share/regripper

- name: copy sift tools directories to /usr/share/sift
  copy:
    src: "{{ item }}"
    dest: /usr/share/sift/
  with_items:
    - /tmp/sift-files/sift/scripts
    - /tmp/sift-files/sift/other
    - /tmp/sift-files/sift/images
    - /tmp/sift-files/sift/audio
    - /tmp/sift-files/sift/resources

- name: copy regripper files to /usr/share/regripper
  copy:
    src: "{{ item }}"
    dest: /usr/share/regripper/
  with_items:
    - /tmp/sift-files/regripper/rip.pl
    - /tmp/sift-files/regripper/plugins

- name: ensure /usr/local/bin/id absent
  file: dest=/usr/local/bin/id state=absent

# Install rc.local patch for more loopback devices
# fixes https://github.com/sans-dfir/sift/issues/22
- name: apply patch to one file
  patch: >
    src=/tmp/sift-files/patches/rc.local.patch
    dest=/etc/rc.local
    remote_src=True
  ignore_errors: true

- name: sift fixubuntu.sh
  command: bash fixubuntu.sh chdir=/tmp/sift-files
  ignore_errors: true

