---

## https://askubuntu.com/questions/588721/ubuntu-14-04-login-loop-issue
- name: check if .Xauthority
  command: "find /home/ -iname .Xauthority"
  register: xauthfiles
  changed_when: false
  ignore_errors: true
  become: yes
- block:
    - name: clean .Xauthority files
      file: dest={{ item }} state=absent
      with_items: "{{ xauthfiles.stdout_lines | default([]) }}"
  when: xauthfiles is defined and xauthfiles.stdout_lines is defined and xauthfiles.stdout_lines

## /var/log/syslog: lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open
##      shared object file: No such file or directory
- name: disable kwallet in pam - not using kde
  replace:
    dest: "{{ item }}"
    regexp: '^([^#].*) pam_kwallet.so(.*)'
    replace: '#\1 pam_kwallet.so\2'
    mode: '0644'
  with_items:
    - /etc/pam.d/lightdm
    - /etc/pam.d/lightdm-greeter

## /var/log/syslog: lightdm: pam_winbind(lightdm:auth): request wbcLogonUser failed: WBC_ERR_AUTH_ERROR,
##      PAM error: PAM_USER_UNKNOWN (10), NTSTATUS: NT_STATUS_NO_SUCH_USER, Error message was: No such user
## BUG: can't login if enabled... probably better to just remove winbind package?
# - name: disable winbind in pam - not using winbind/AD auth
#   replace:
#     dest: "{{ item }}"
#     regexp: "^([^#].*)([\\s]*)pam_winbind.so(.*)"
#     replace: '#\1\2pam_winbind.so\3'
#   with_items:
#     - /etc/pam.d/common-account
#     - /etc/pam.d/common-auth
#     - /etc/pam.d/common-password
#     - /etc/pam.d/common-session
#     - /etc/pam.d/common-session-noninteractive
