---

# to avoid error at install. unity only? (bluez* gnome-bluetooth* gnome-user-share* indicator-bluetooth*
#       unity-control-center* unity-control-center-signon*)
# bluez package
# systemctl disable bluetooth.service
- name: Bluez package install
  ansible.builtin.apt:
    name: bluez
    state: present
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success
- name: Disable bluetooth service
  ansible.builtin.service: name=bluetooth state=stopped enabled=no

- name: SIFT x11 packages install (lxde)
  ansible.builtin.apt:
    name:
      - xinit
      - lxde
      - lxdm
    state: present
  when: sift_x11_env is defined and sift_x11_env and ansible_distribution_release == 'xenial'
  ## mostly for travis to avoid stalling "No output has been received in the last 10m0s"...
  async: 600
  poll: 15
  register: pkg_result
  until: pkg_result is success

- name: X11 ensure desktop-directories exists
  ansible.builtin.file:
    dest: "/home/{{ sift_user }}/.local/share/desktop-directories"
    mode: '0700'
    owner: "{{ sift_user }}"
    state: directory
- name: Adding sift directory shortcut
  ansible.builtin.copy:
    src: sift.directory
    dest: "/home/{{ sift_user }}/.local/share/desktop-directories/sift.directory"
    mode: '0644'
    owner: "{{ sift_user }}"

- name: Ensure unity-greeter directory exists
  ansible.builtin.file: dest=/usr/share/unity-greeter state=directory mode=0755
- name: Check if /usr/share/unity-greeter/logo.png exists
  ansible.builtin.stat: path=/usr/share/unity-greeter/logo.png
  register: logoubuntu1
- name: Check if /usr/share/unity-greeter/logo.png.ubuntu exists
  ansible.builtin.stat: path=/usr/share/unity-greeter/logo.png.ubuntu
  register: logoubuntu2
- name: Backup ubuntu unity greeter logo
  ansible.builtin.copy:
    src: /usr/share/unity-greeter/logo.png
    dest: /usr/share/unity-greeter/logo.png.ubuntu
    owner: "{{ sift_user }}"
    mode: '0644'
    remote_src: true
  when: not logoubuntu2.stat.exists and logoubuntu1.stat.exists
- name: Copy sift unity greeter logo
  ansible.builtin.copy:
    src: /usr/share/sift/images/login_logo.png
    dest: /usr/share/unity-greeter/logo.png
    owner: "{{ sift_user }}"
    mode: '0644'
    remote_src: true
  when: not logoubuntu1.stat.exists

- name: Setting up auto-login for user {{ sift_user }}
  ansible.builtin.lineinfile:
    dest: '/etc/lxdm/lxdm.conf'
    regexp: "{{ item.regexp }}"
    line: "{{ item.replace }}"
    mode: '0644'
    create: true
  with_items:
    - { regexp: '^autologin=.*', replace: "autologin={{ sift_user }}" }
    - { regexp: '^disable=.*', replace: 'disable=1' }
  when: sift_autologin

## Manual or alternative
## https://github.com/jistr/ansible-gsetting
## https://github.com/JBKahn/provisioning-local/tree/master/ansible_modules/{dconf,gconftool-2,gsettings}
- name: SIFT Wallpaper Configuration
  ansible.builtin.command: "gsettings set org.gnome.desktop.background picture-uri file:///usr/share/sift/images/forensics_blue.jpg"
  become: yes
  become_user: "{{ sift_user }}"
  when: sift_x11_background is defined and sift_x11_background

- name: SIFT X11 | set launcher favorites
  dconf:
    key: /com/canonical/unity/launcher/favorites
    value: "{{ sift_x11_launcher_favorites }}"
    state: present
  become: yes
  become_user: "{{ sift_user }}"
  when: sift_x11_env is defined and sift_x11_env
  failed_when: false

- name: Autostart folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ sift_user }}"
    group: "{{ sift_user }}"
  with_items:
    - "/home/{{ sift_user }}/.config/autostart"

- name: Check if /usr/share/sift/other/gnome-terminal.desktop exists
  ansible.builtin.stat: path=/usr/share/sift/other/gnome-terminal.desktop
  register: gtd
- name: Autostart sift gnome-terminal
  ansible.builtin.copy:
    src: /usr/share/sift/other/gnome-terminal.desktop
    dest: "/home/{{ sift_user }}/.config/autostart/gnome-terminal.desktop"
    owner: "{{ sift_user }}"
    mode: '0644'
    remote_src: true
  when: gtd.stat.exists

- name: Symlink sift forensics background
  ansible.builtin.file:
    src: /usr/share/sift/images/forensics_blue.jpg
    dest: /usr/share/backgrounds/warty-final-ubuntu.png
    mode: '0644'
    state: link
    force: yes
  when: sift_x11_background is defined and sift_x11_background
