---

#to avoid error at install. unity only?
#bluez package
#systemctl disable bluetooth.service

- name: Trusty | SIFT x11 packages install (unity)
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - xinit
    - ubuntu-desktop
    - ubuntu-session
## conflicts file /usr/bin/vba_extract.py between python-xlsxwriter (required by plaso, python-plaso) and python3-xlsxwriter (required by ubuntu-desktop chain)
  when: sift_x11_env is defined and sift_x11_env and ansible_distribution_release == 'trusty'

- name: Xenial | SIFT x11 packages install (lxde)
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - xinit
    - lxde
    - lxdm
  when: sift_x11_env is defined and sift_x11_env and ansible_distribution_release == 'xenial'

- name: x11 ensure desktop-directories exists
  file: dest=/home/{{ sift_user }}/.local/share/desktop-directories mode=0700 owner={{ sift_user }} state=directory
- name: adding sift directory shortcut
  copy: src=sift.directory dest=/home/{{ sift_user }}/.local/share/desktop-directories/sift.directory mode=0644 owner={{ sift_user }}

