# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # config.vm.box = "ubuntu/jammy64"
    config.vm.box = "ubuntu/bionic64"
    #config.vm.box = "generic/centos9s"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant', ansible_python_interpreter: '/usr/bin/python3' }
       ansible.groups = {
          "myrole" => ["sift" ],
       }
    end

    config.vm.define "sift" do |sift|
        sift.vm.hostname = "sift"
        sift.vm.provider "virtualbox" do |v|
          v.memory = 2048
        end
    end

end
